Repository blimpan/DD2480-SWEF, pull requests merged in 2025-01, with the labels that each got.

#8 Added rough Java implementation of C code provided in assignment PDF.
  DECIDE.java
Labels: enhancement

#14 Add function to Parameter class that sets values for all variables
  DECIDE.java
Labels: enhancement

#19 Add basic test file
  .gitignore
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#20 Add function for LIC3
  LaunchInterceptor.java
Labels: enhancement

#27 Main code refactoring #26
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: refactor

#31 Update devloppement branch
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#32 Update devloppement branch
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#33 Update devloppement branch
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#53 fix: Add absolute value for area calculation in computeTriangleArea
  LaunchInterceptor.java
Labels: bug

#64 Fix LaunchInterceptor.java inverted condition #63
  LaunchInterceptor.java
Labels: bug

#66 Fix main branch compilation
  LaunchInterceptor.java
Labels: bug

#67 Implemented LIC14
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#68 Implemented LIC12
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#70 Added tests for LIC4.
  LaunchInterceptorTEST.java
Labels: enhancement

#71 Added tests for LIC5.
  LaunchInterceptorTEST.java
Labels: enhancement

#77 LIC10 Unit Test Implemeted and Passed Tests
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#62 Added helper function
  LaunchInterceptor.java
Labels: enhancement

#88 Implemented LIC13
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement

#94 Finished on the README and Code Documentation
  CodeDocumentation.md
  Cover.jpg
  README.md
Labels: documentation

#101 Fixed errors in tests for LIC0.
  LaunchInterceptorTEST.java
Labels: bug, invalid

#93 Implement decide
  LaunchInterceptor.java
  LaunchInterceptorTEST.java
Labels: enhancement, refactor

#111 Refactor Test file
  LaunchInterceptorTest.java
Labels: refactor

#120 Fix Inverted boolean
  LaunchInterceptor.java
  LaunchInterceptorTest.java
Labels: bug

#123 Documentation LIC 12 to 14 & Constructor
  LaunchInterceptor.java
Labels: documentation

#121 Implement main method
  Main.java
Labels: enhancement

#97 Completed the README and Code Documentation
  CodeDocumentation.md
  README.md
  Resources/.gitignore
  Resources/Cover.jpg
Labels: documentation

#136 Refactor file structure
  src/LaunchInterceptor.java
  src/Main.java
  test/LaunchInterceptorTest.java
Labels: refactor

#138 Update README.md based on lab reviews
  README.md
Labels: documentation
